package demo;

import dataModel.column.*;
import dataModel.table.DataObjectInterface;
import dataModel.table.DataTable;
import dataModel.table.DataTableInterface;


/********************************************************
 *
 *    ContractAnnotation - Data Table
 *    Automatically generated file by GenerateTable.java
 *
 *
 */

public class DemoItem2Table extends DataTable implements DataTableInterface {

    private static final String _TITLE = "Demo Table2";
    public static final String _TABLE = "demo2";
    private static final String _DESCRIPTION = "Another a test";

    public enum Columns {Name, Ordinal }

    public static final ColumnStructureInterface[] _DATA = new ColumnStructureInterface[] {

            new StringColumn("Name",        DisplayFormat.REGULAR),
            new IntColumn("Ordinal",        DisplayFormat.REGULAR),
    };

    public DemoItem2Table(){

        init(_DATA, _TABLE, _TITLE, _DESCRIPTION, _DefaultValues, _TestValues);
    }


    private static final DataObjectInterface[] _DefaultValues = {

            new DemoItem2("xxx", 4711),



    };
    private static final DataObjectInterface[] _TestValues = {



    };


    /* Code below this point will not be replaced when regenerating the file*/

    /*__endAutoGenerated*/



}
